import React from "react";
import { Link } from "react-router";
import { ArrowLeft } from "lucide-react";
import { Navbar } from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";
import ScrollToTop from "@/components/ScrollToTop";

const LAST_UPDATED = "April 5, 2025";

const EMAIL = "mayurkamble0250@gmail.com";

const sections = [
  {
    id: "information-we-collect",
    title: "1. Information We Collect",
    content: [
      `We collect information you provide directly to us when you create an account, such as your name, email address, and password. We also collect the content you save to Mindfolio, including URLs, images, PDF files, and text notes, as well as the metadata associated with that content (e.g., titles, timestamps, tags generated by our AI).`,
      `We automatically collect certain technical information when you use the Service, including your IP address, browser type, operating system, referring URLs, device identifiers, and cookie data. We also collect information about how you interact with the Service, such as the pages you visit and the features you use.`,
      `We do not intentionally collect sensitive personal information such as health data, financial account numbers, or government identification numbers. Please do not submit such information to the Service.`,
    ],
  },
  {
    id: "how-we-use",
    title: "2. How We Use Your Information",
    content: [
      `We use the information we collect to provide, maintain, and improve the Service, including to process the content you save, generate AI-powered summaries and tags, and enable semantic search across your personal knowledge base. Your content is processed on your behalf and is not used to train our own AI models.`,
      `We use your email address to send you account-related notifications, security alerts, and, if you have opted in, product updates and newsletters. You may opt out of marketing communications at any time by using the unsubscribe link in those emails.`,
      `We analyze aggregate, anonymized usage data to understand how users interact with Mindfolio, diagnose technical problems, and inform product development decisions. This analysis does not involve reviewing the personal content of individual users.`,
      `We may use your information to comply with applicable laws and regulations, respond to legal process or requests from law enforcement, and protect the rights, property, or safety of Mindfolio, our users, or the public.`,
    ],
  },
  {
    id: "third-party",
    title: "3. Third-Party Data Processors",
    content: [
      `Mindfolio relies on a number of trusted third-party services to deliver its functionality. By using the Service, you acknowledge that your data may be processed by these sub-processors in accordance with their own privacy policies.`,
      `Mistral AI is used to power the core intelligence of Mindfolio, including generating text summaries, extracting key entities and topics, and creating vector embeddings for semantic search. When you save a new item, its content may be transmitted to Mistral AI's API for processing. Mistral AI does not use your data for model training under their enterprise data processing agreements.`,
      `RapidAPI is used to facilitate scraping and data extraction from social media platforms such as Instagram. When you save a social media link, a request may be routed through RapidAPI's aggregation layer to retrieve the associated media and metadata. You can review RapidAPI's privacy policy on their website.`,
      `MongoDB Atlas is our primary database provider, hosting the structured data associated with your account and saved items on cloud infrastructure. MongoDB Atlas maintains SOC 2 Type II compliance and encrypts all data at rest and in transit. For media files (images, PDFs), we use ImageKit for storage and content delivery.`,
    ],
    list: [
      "Mistral AI — AI processing, summarization, and embeddings",
      "RapidAPI — Social media data extraction gateway",
      "MongoDB Atlas — Primary database and data storage",
      "ImageKit — Media file storage and CDN delivery",
    ],
  },
  {
    id: "retention",
    title: "4. Data Retention & Deletion",
    content: [
      `We retain your personal information and saved content for as long as your account is active or as needed to provide you with the Service. If you close your account, we will delete or anonymize your personal information within 30 days, except where we are required to retain it for legitimate legal, tax, or business purposes.`,
      `Individual items can be deleted at any time from within the application. Deletion from our primary database (MongoDB) is immediate upon confirmation. Cached or derived data (such as AI embeddings stored in our vector database) and media files stored on ImageKit are purged within 7 business days following a deletion request.`,
      `Please note that due to the nature of distributed systems and backup retention policies, deleted content may persist in encrypted backups for up to 90 days before being permanently overwritten. These backups are not accessible to users or used to restore deleted content without your express request.`,
    ],
  },
  {
    id: "your-rights",
    title: "5. Your Rights",
    content: [
      `Depending on your jurisdiction, you may have certain rights with respect to your personal information. These may include the right to access a copy of the personal data we hold about you; the right to correct inaccurate or incomplete data; the right to request deletion of your personal data; the right to restrict or object to our processing of your data; and the right to data portability.`,
      `To exercise any of these rights, please contact us at privacy@mindfolio.app. We will respond to all verifiable requests within 30 days. We may need to verify your identity before processing your request to protect the security of your account.`,
      `If you are a resident of the European Economic Area (EEA) or the United Kingdom, you have the right to lodge a complaint with your local data protection authority if you believe our processing of your personal data infringes applicable data protection law. We encourage you to contact us first so we can address your concerns directly.`,
    ],
  },
];

const LegalPrivacy = () => {
  return (
    <div className="min-h-screen bg-background text-foreground flex flex-col">
      <Navbar />

      <main className="flex-1 pt-28 pb-24">
        <div className="max-w-3xl mx-auto px-6 md:px-8">
          {/* Back link */}
          <Link
            to="/landing"
            className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-primary transition-colors mb-12 group"
          >
            <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-0.5" />
            Back to Home
          </Link>

          {/* Header */}
          <div className="mb-12 border-b border-border pb-10">
            <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-foreground mb-4">
              Privacy Policy
            </h1>
            <p className="text-sm text-muted-foreground">
              Last updated: {LAST_UPDATED}
            </p>
          </div>

          {/* Intro */}
          <p className="text-muted-foreground leading-relaxed mb-10 text-base">
            At Mindfolio, your privacy is a foundational principle, not an
            afterthought. This Privacy Policy explains what information we
            collect, how we use it, and what choices you have. We process your
            data only to provide you with a better, more intelligent second
            brain — never to sell it.
          </p>

          {/* Sections */}
          <div className="space-y-12">
            {sections.map((section) => (
              <section key={section.id} id={section.id}>
                <h2 className="text-2xl font-semibold mt-2 mb-4 text-foreground">
                  {section.title}
                </h2>
                <div className="space-y-4">
                  {section.content.map((paragraph, i) => (
                    <p
                      key={i}
                      className="text-muted-foreground leading-relaxed text-base"
                    >
                      {paragraph}
                    </p>
                  ))}
                </div>

                {/* Optional bullet list (used for third-party section) */}
                {section.list && (
                  <ul className="mt-4 space-y-2 pl-5">
                    {section.list.map((item, i) => (
                      <li
                        key={i}
                        className="text-muted-foreground leading-relaxed text-base list-disc"
                      >
                        {item}
                      </li>
                    ))}
                  </ul>
                )}
              </section>
            ))}
          </div>

          {/* Contact footer note */}
          <div className="mt-16 pt-10 border-t border-border">
            <p className="text-sm text-muted-foreground leading-relaxed">
              If you have questions or concerns about this Privacy Policy or our
              data practices, please contact our Privacy Team at{" "}
              <a
                href={`mailto:${EMAIL}`}
                className="text-primary hover:underline underline-offset-4"
              >
                {EMAIL}
              </a>
              .
            </p>
          </div>
        </div>
      </main>

      <Footer />
      <ScrollToTop />
    </div>
  );
};

export default LegalPrivacy;
