import mongoose from "mongoose";

const itemSchema = new mongoose.Schema(
  {
    // 1. Core Relationship & Metadata
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "users",
      required: true,
      index: true, // CRITICAL: Makes loading a user's feed lightning fast
    },
    url: {
      type: String,
      required: false,
    },
    sourceLink: {
      type: String,
      required: false,
    },
    type: {
      type: String,
      enum: [
        "web",
        "images",
        "videos",
        "documents",
        "articles",
        "notes",
        "youtube",
        "quotes",
        "posts",
        "snippets",
        "other",
      ],
      default: "other",
    },
    status: {
      type: String,
      enum: ["pending", "processing", "completed", "failed"],
      default: "pending", // Starts pending when saved, updates when worker finishes
    },

    // 2. Extracted Content (Filled by your scraper)
    title: {
      type: String,
    },
    textContent: {
      type: String, // The clean, readable text stripped of HTML/ads
      select: false, // Don't send this massive string to the frontend unless explicitly asked for!
    },
    thumbnailUrl: {
      type: String, // For displaying in your masonry grid
    },
    author: {
      type: String,
    },

    // 3. AI Generated Data (Filled by Gemini)
    summary: {
      type: String,
    },
    aiTags: {
      type: [String], // Array of strings like ["React", "Machine Learning"]
      index: true, // Index this so users can click a tag and filter instantly
    },
    embedding: {
      type: [Number], // The array of floats generated by the AI for semantic search
      select: false, // Hide this from frontend queries to save huge amounts of bandwidth
    },

    // 4. User Organization (Optional features they can add later)
    isFavorite: {
      type: Boolean,
      default: false,
    },
    userNotes: {
      type: String, // If the user wants to add their own thoughts
    },
  },
  {
    timestamps: true,
  },
);

// Optional: Compound index to prevent users from saving the exact same URL twice
itemSchema.index(
  { userId: 1, url: 1 },
  {
    unique: true,
    // CRITICAL: Only enforce uniqueness if the URL actually exists and is a string
    partialFilterExpression: { url: { $type: "string" } },
  },
);

export const itemModel = mongoose.model("items", itemSchema);
